force-app/chapter00/default/objects/Asset_Residency__c/Asset_Residency__c.object-meta.xml
<CustomObject>
    <description>An sObject to track where an asset was located and for how long.</description>
    <label>Asset Residency</label>
    <nameField>
        <displayFormat>ARN-{00000}</displayFormat>
        <label>Asset Residency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Residencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/chapter00/default/objects/Asset_Residency__c/fields/Resident_Account__c.field-meta.xml
<CustomField>
    <fullName>Resident_Account__c</fullName>
    <description>The account that the asset is residing at.</description>
    <label>Resident Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Asset Residencies</relationshipLabel>
    <relationshipName>Asset_Residencies</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/chapter02/default/classes/AssetMapBusinessLogic.cls
public with sharing class AssetMapBusinessLogic {
    public static List<LocationWrapper> getLocationWrappers(Id assetId) {
        List<LocationWrapper> mapMarkers = new List<LocationWrapper>();
        List<Asset_Residency__c> residencyList = AssetMapAccess.getResidencies(assetId);

        for(Asset_Residency__c residency : residencyList) {
            mapMarkers.add(new LocationWrapper(residency));
        }

        return mapMarkers;
    }

    public class LocationWrapper {
        @AuraEnabled public MarkerWrapper location;
        @AuraEnabled public String value;
        @AuraEnabled public String title;

        public LocationWrapper(Asset_Residency__c residency) {
            this.location = new MarkerWrapper(residency);
            this.title = residency.Resident_Account__r.Name;
            this.value = residency.Name;
        }
    }

    public class MarkerWrapper {
        @AuraEnabled public String Latitude;
        @AuraEnabled public String Longitude;

        public MarkerWrapper(Asset_Residency__c residency) {
            this.Latitude = String.valueOf(residency.Resident_Account__r.Museum_Office__Latitude__s);
            this.Longitude = String.valueOf(residency.Resident_Account__r.Museum_Office__Longitude__s);
        }
    }
}