force-app/chapter00/default/objects/Asset/fields/Accession_Number__c.field-meta.xml
<CustomField>
    <fullName>Accession_Number__c</fullName>
    <description>The Accession Number, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Accession Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Accession_Year__c.field-meta.xml
<CustomField>
    <fullName>Accession_Year__c</fullName>
    <description>The Accession Year for an object, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Accession Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Asset_URL__c.field-meta.xml
<CustomField>
    <fullName>Asset_URL__c</fullName>
    <description>The asset&apos;s URL, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Asset URL</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Asset_Wikidata_URL__c.field-meta.xml
<CustomField>
    <fullName>Asset_Wikidata_URL__c</fullName>
    <description>The asset&apos;s Wikidata URL, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Asset Wikidata URL</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>The classification of the asset, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Classification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Culture__c.field-meta.xml
<CustomField>
    <fullName>Culture__c</fullName>
    <description>The originating culture of the asset, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Culture</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The Department the asset is located in, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Is_Highlight__c.field-meta.xml
<CustomField>
    <fullName>Is_Highlight__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The Is Highlight field on an Object as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Is Highlight</label>
    <type>Checkbox</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Is_Public_Domain__c.field-meta.xml
<CustomField>
    <fullName>Is_Public_Domain__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The determination as to whether an asset is in the public domain, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Is Public Domain</label>
    <type>Checkbox</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Medium__c.field-meta.xml
<CustomField>
    <fullName>Medium__c</fullName>
    <description>The medium of the asset, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Medium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Object_ID__c.field-meta.xml
<CustomField>
    <fullName>Object_ID__c</fullName>
    <description>The Object ID for an asset, provided by The Metropolitan&apos;s Open Access API.</description>
    <externalId>true</externalId>
    <label>Object ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <description>The time period of the asset, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Period</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Primary_Constituent__c.field-meta.xml
<CustomField>
    <fullName>Primary_Constituent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Constituent representing the Artist of the work, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Primary Constituent</label>
    <referenceTo>Constituent__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Primary_Image__c.field-meta.xml
<CustomField>
    <fullName>Primary_Image__c</fullName>
    <description>The Primary Image URL as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Primary Image</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Primary_Image_Small__c.field-meta.xml
<CustomField>
    <fullName>Primary_Image_Small__c</fullName>
    <description>The URL for the small version of the Primary Image, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Primary Image Small</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary asset tag, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Tag</label>
    <referenceTo>Tag__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/chapter00/default/objects/Constituent__c/Constituent__c.object-meta.xml
<CustomObject>
    <description>A custom object to hold information about the artist for each asset.</description>
    <label>Constituent</label>
    <nameField>
        <label>Constituent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constituents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/chapter00/default/objects/Constituent__c/fields/Constituent_ID__c.field-meta.xml
<CustomField>
    <fullName>Constituent_ID__c</fullName>
    <description>The external ID for The Metropolitan&apos;s Open Access database.</description>
    <externalId>true</externalId>
    <label>Constituent ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/chapter00/default/objects/Constituent__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>The gender of the constituent.</description>
    <label>Gender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Constituent__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>The role that the Constituent played in the creation of the asset.</description>
    <label>Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Constituent__c/fields/ULAN_URL__c.field-meta.xml
<CustomField>
    <fullName>ULAN_URL__c</fullName>
    <description>The ULAN URL for the constituent.</description>
    <label>ULAN URL</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Constituent__c/fields/Wikidata_URL__c.field-meta.xml
<CustomField>
    <fullName>Wikidata_URL__c</fullName>
    <description>The Wikidata URL for the constituent.</description>
    <label>Wikidata URL</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <description>An object to classify assets by tag.</description>
    <label>Tag</label>
    <nameField>
        <label>Tag Term</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/chapter00/default/objects/Tag__c/fields/AAT__c.field-meta.xml
<CustomField>
    <fullName>AAT__c</fullName>
    <description>The AAT number, as provided by The Metropolitan&apos;s Open Access API.</description>
    <formula>SUBSTITUTE(AAT_URL__c, &apos;http://vocab.getty.edu/page/aat/&apos;, &apos;&apos;)</formula>
    <label>AAT</label>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Tag__c/fields/AAT_URL__c.field-meta.xml
<CustomField>
    <fullName>AAT_URL__c</fullName>
    <description>The AAT URL for the asset tag, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>AAT URL</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Tag__c/fields/Wikidata_URL__c.field-meta.xml
<CustomField>
    <fullName>Wikidata_URL__c</fullName>
    <description>The Wikidata URL for the asset tag, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Wikidata URL</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/classes/OrgSetupREST.cls
public with sharing class OrgSetupREST {

    private static final String AAT_URL_STRING = 'http://vocab.getty.edu/page/aat/';
    public static Util_DML dmlUtil = new Util_DML();

    @future(callout=true)
    public static void getAssets(String objectId, Id accountId) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:The_Met_Named/objects/' + objectId);
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        // If the request is successful, parse the JSON response.

        System.debug(response.getBody());

        ObjectWrappers.AssetWrapper assetWrapper = (ObjectWrappers.AssetWrapper) JSON.deserialize(response.getBody(), ObjectWrappers.AssetWrapper.Class);

        Constituent__c constituentToUpsert = new Constituent__c();
        Tag__c tagToUpsert = new Tag__c();
        Asset assetToUpsert = new Asset();

        if(assetWrapper.constituents != null) {
            constituentToUpsert.Name = assetWrapper.constituents[0].name;
            constituentToUpsert.Constituent_Id__c = assetWrapper.constituents[0].constituentID;
            constituentToUpsert.Gender__c = assetWrapper.constituents[0].gender;
            constituentToUpsert.Role__c = assetWrapper.constituents[0].role;
            constituentToUpsert.ULAN_URL__c = assetWrapper.constituents[0].constituentULAN_URL;
            constituentToUpsert.Wikidata_URL__c = assetWrapper.constituents[0].constituentWikidata_URL;

            try{
                dmlUtil.upsertRecords(new List<Constituent__c>{constituentToUpsert}, 'Constituent_Id__c');
            } catch (Exception e) {
                System.debug(e.getMessage());
            }
        }

        if(assetWrapper.tags != null) {
            tagToUpsert.Name = assetWrapper.tags[0].term;
            tagToUpsert.AAT__c = assetWrapper.tags[0].AAT_URL.removeStart(AAT_URL_STRING);
            tagToUpsert.AAT_URL__c = assetWrapper.tags[0].AAT_URL;
            tagToUpsert.Wikidata_URL__c = assetWrapper.tags[0].Wikidata_URL;

            try {
                dmlUtil.upsertRecords(new List<Tag__c>{tagToUpsert}, 'AAT__c');
            } catch (Exception e) {
                System.debug(e.getMessage());
            }
        }

        assetToUpsert.Accession_Number__c = assetWrapper.accessionNumber;
        assetToUpsert.Accession_Year__c = assetWrapper.accessionYear;
        assetToUpsert.Is_Public_Domain__c = assetWrapper.isPublicDomain;
        assetToUpsert.AccountId = accountId;
        assetToUpsert.Name = assetWrapper.title;
        assetToUpsert.Asset_URL__c = assetWrapper.objectURL;
        assetToUpsert.Asset_Wikidata_URL__c = assetWrapper.objectWikidata_URL;
        assetToUpsert.Classification__c = assetWrapper.classification;
        assetToUpsert.Culture__c = assetWrapper.culture;
        assetToUpsert.Department__c = assetWrapper.department;
        assetToUpsert.Is_Highlight__c = assetWrapper.isHighlight;
        assetToUpsert.Medium__c = assetWrapper.medium;
        assetToUpsert.Object_ID__c = assetWrapper.objectId;
        assetToUpsert.Period__c = assetWrapper.period;
        assetToUpsert.Primary_Image__c = assetWrapper.primaryImage;
        assetToUpsert.Primary_Image_Small__c = assetWrapper.primaryImageSmall;
        assetToUpsert.Primary_Constituent__c = constituentToUpsert.Id;
        assetToUpsert.Tag__c = tagToUpsert.Id;

        try{
            dmlUtil.upsertRecords(new List<Asset>{assetToUpsert}, 'Object_ID__c');
        } catch (Exception e) {
        System.debug(e.getMessage());
        }
    }
}