force-app/chapter00/default/objects/Asset/fields/Accession_Number__c.field-meta.xml
<CustomField>
    <fullName>Accession_Number__c</fullName>
    <description>The Accession Number, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Accession Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Accession_Year__c.field-meta.xml
<CustomField>
    <fullName>Accession_Year__c</fullName>
    <description>The Accession Year for an object, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Accession Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Asset_URL__c.field-meta.xml
<CustomField>
    <fullName>Asset_URL__c</fullName>
    <description>The asset&apos;s URL, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Asset URL</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Asset_Wikidata_URL__c.field-meta.xml
<CustomField>
    <fullName>Asset_Wikidata_URL__c</fullName>
    <description>The asset&apos;s Wikidata URL, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Asset Wikidata URL</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>The classification of the asset, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Classification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Culture__c.field-meta.xml
<CustomField>
    <fullName>Culture__c</fullName>
    <description>The originating culture of the asset, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Culture</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The Department the asset is located in, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Is_Highlight__c.field-meta.xml
<CustomField>
    <fullName>Is_Highlight__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The Is Highlight field on an Object as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Is Highlight</label>
    <type>Checkbox</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Is_Public_Domain__c.field-meta.xml
<CustomField>
    <fullName>Is_Public_Domain__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The determination as to whether an asset is in the public domain, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Is Public Domain</label>
    <type>Checkbox</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Medium__c.field-meta.xml
<CustomField>
    <fullName>Medium__c</fullName>
    <description>The medium of the asset, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Medium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Object_ID__c.field-meta.xml
<CustomField>
    <fullName>Object_ID__c</fullName>
    <description>The Object ID for an asset, provided by The Metropolitan&apos;s Open Access API.</description>
    <externalId>true</externalId>
    <label>Object ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <description>The time period of the asset, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Period</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Primary_Constituent__c.field-meta.xml
<CustomField>
    <fullName>Primary_Constituent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Constituent representing the Artist of the work, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Primary Constituent</label>
    <referenceTo>Constituent__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Primary_Image__c.field-meta.xml
<CustomField>
    <fullName>Primary_Image__c</fullName>
    <description>The Primary Image URL as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Primary Image</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Primary_Image_Small__c.field-meta.xml
<CustomField>
    <fullName>Primary_Image_Small__c</fullName>
    <description>The URL for the small version of the Primary Image, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Primary Image Small</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary asset tag, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Tag</label>
    <referenceTo>Tag__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/chapter00/default/objects/Constituent__c/Constituent__c.object-meta.xml
<CustomObject>
    <description>A custom object to hold information about the artist for each asset.</description>
    <label>Constituent</label>
    <nameField>
        <label>Constituent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constituents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/chapter00/default/objects/Constituent__c/fields/Constituent_ID__c.field-meta.xml
<CustomField>
    <fullName>Constituent_ID__c</fullName>
    <description>The external ID for The Metropolitan&apos;s Open Access database.</description>
    <externalId>true</externalId>
    <label>Constituent ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/chapter00/default/objects/Constituent__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>The gender of the constituent.</description>
    <label>Gender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Constituent__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>The role that the Constituent played in the creation of the asset.</description>
    <label>Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Constituent__c/fields/ULAN_URL__c.field-meta.xml
<CustomField>
    <fullName>ULAN_URL__c</fullName>
    <description>The ULAN URL for the constituent.</description>
    <label>ULAN URL</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Constituent__c/fields/Wikidata_URL__c.field-meta.xml
<CustomField>
    <fullName>Wikidata_URL__c</fullName>
    <description>The Wikidata URL for the constituent.</description>
    <label>Wikidata URL</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <description>An object to classify assets by tag.</description>
    <label>Tag</label>
    <nameField>
        <label>Tag Term</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/chapter00/default/objects/Tag__c/fields/AAT__c.field-meta.xml
<CustomField>
    <fullName>AAT__c</fullName>
    <description>The AAT number, as provided by The Metropolitan&apos;s Open Access API.</description>
    <formula>SUBSTITUTE(AAT_URL__c, &apos;http://vocab.getty.edu/page/aat/&apos;, &apos;&apos;)</formula>
    <label>AAT</label>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Tag__c/fields/AAT_URL__c.field-meta.xml
<CustomField>
    <fullName>AAT_URL__c</fullName>
    <description>The AAT URL for the asset tag, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>AAT URL</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Tag__c/fields/Wikidata_URL__c.field-meta.xml
<CustomField>
    <fullName>Wikidata_URL__c</fullName>
    <description>The Wikidata URL for the asset tag, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Wikidata URL</label>
    <type>Url</type>
</CustomField>

force-app/chapter05/default/classes/AddAssetService.cls
public with sharing class AddAssetService {
    
    private static final String AAT_URL_STRING = 'http://vocab.getty.edu/page/aat/';
    private Assets assets = new Assets();
    private Constituents constituents = new Constituents();
    private Tags tags = new Tags();

    public DepartmentsWrapper getDepartmentWrappers() {
        return (DepartmentsWrapper) JSON.deserialize(AddAssetAPI.getDepartments(), DepartmentsWrapper.Class);
    }

    public List<ObjectWrappers.AssetWrapper> getSearchedAssets(String searchTerm, Integer departmentId) {
        SearchWrapper searchWrap = (SearchWrapper) JSON.deserialize(AddAssetAPI.searchByTerm(searchTerm, departmentId), SearchWrapper.Class);

        List<ObjectWrappers.AssetWrapper> assetWrapperList = new List<ObjectWrappers.AssetWrapper>();

        if(searchWrap.objectIDs != null) {
            for(Integer objId : searchWrap.objectIDs) {
                ObjectWrappers.AssetWrapper assetWrapper = (ObjectWrappers.AssetWrapper) JSON.deserialize(AddAssetAPI.getSearchedAssetInfo(objId), ObjectWrappers.AssetWrapper.Class);
                assetWrapperList.add(assetWrapper);
            }
    
            return assetWrapperList;
        }

        return null;
    }

    public ObjectWrappers.AssetWrapper getSearchedAssetWrapper(Integer objectId) {
        return (ObjectWrappers.AssetWrapper) JSON.deserialize(AddAssetAPI.getSearchedAssetInfo(objectId), ObjectWrappers.AssetWrapper.Class);
    }

    public Map<Integer, String> upsertAssetsAndReturnInfoMap(List<ObjectWrappers.AssetWrapper> assetWrappers, Id accountId) {
        List<Asset> assetsToUpsert = new List<Asset>();
        List<Constituent__c> constituentsToUpsert = new List<Constituent__c>();
        List<Tag__c> tagsToUpsert = new List<Tag__c>();

        Map<String, String> assetIdToConstituentIdMap = new Map<String, String>();
        Map<String, String> assetIdToTagIdMap = new Map<String, String>();

        for(ObjectWrappers.AssetWrapper assetWrapper : assetWrappers) {
            Constituent__c constituentToUpsert = new Constituent__c();
            Tag__c tagToUpsert = new Tag__c();
            Asset assetToUpsert = new Asset();

            if(assetWrapper.constituents != null) {
                constituentToUpsert.Name = nullCheck(assetWrapper.constituents[0].name);
                constituentToUpsert.Constituent_Id__c = nullCheck(assetWrapper.constituents[0].constituentID);
                constituentToUpsert.Gender__c = nullCheck(assetWrapper.constituents[0].gender);
                constituentToUpsert.Role__c = nullCheck(assetWrapper.constituents[0].role);
                constituentToUpsert.ULAN_URL__c = nullCheck(assetWrapper.constituents[0].constituentULAN_URL);
                constituentToUpsert.Wikidata_URL__c = nullCheck(assetWrapper.constituents[0].constituentWikidata_URL);

                constituentsToUpsert.add(constituentToUpsert);
            }

            if(assetWrapper.tags != null) {
                tagToUpsert.Name = nullCheck(assetWrapper.tags[0].term);
                tagToUpsert.AAT__c = nullCheck(assetWrapper.tags[0].AAT_URL).removeStart(AAT_URL_STRING);
                tagToUpsert.AAT_URL__c = nullCheck(assetWrapper.tags[0].AAT_URL);
                tagToUpsert.Wikidata_URL__c = nullCheck(assetWrapper.tags[0].Wikidata_URL);

                tagsToUpsert.add(tagToUpsert);
            } else {
                tagToUpsert.Name = 'No Tag Given';
                tagToUpsert.AAT__c = '99999';
    
                tagsToUpsert.add(tagToUpsert);
            }

            assetToUpsert.Accession_Number__c = assetWrapper.accessionNumber;
            assetToUpsert.Accession_Year__c = assetWrapper.accessionYear == '' ? null : Integer.valueOf(assetWrapper.accessionYear);
            assetToUpsert.Is_Public_Domain__c = assetWrapper.isPublicDomain;
            assetToUpsert.AccountId = Id.valueOf(accountId);
            assetToUpsert.Name = assetWrapper.title;
            assetToUpsert.Asset_URL__c = assetWrapper.objectURL;
            assetToUpsert.Asset_Wikidata_URL__c = assetWrapper.objectWikidata_URL;
            assetToUpsert.Classification__c = assetWrapper.classification;
            assetToUpsert.Culture__c = assetWrapper.culture;
            assetToUpsert.Department__c = assetWrapper.department;
            assetToUpsert.Is_Highlight__c = assetWrapper.isHighlight;
            assetToUpsert.Medium__c = assetWrapper.medium;
            assetToUpsert.Object_ID__c = assetWrapper.objectId;
            assetToUpsert.Period__c = assetWrapper.period;
            assetToUpsert.Primary_Image__c = assetWrapper.primaryImage;
            assetToUpsert.Primary_Image_Small__c = assetWrapper.primaryImageSmall;

            assetIdToConstituentIdMap.put(assetToUpsert.Object_ID__c, constituentToUpsert.Constituent_Id__c);
            assetIdToTagIdMap.put(assetToUpsert.Object_ID__c, tagToUpsert.AAT__c);

            assetsToUpsert.add(assetToUpsert);
        }

        if(constituentsToUpsert.size() > 0) {
            constituents.upsertConstituents(constituentsToUpsert);
        }

        if(tagsToUpsert.size() > 0) {
            tags.upsertTags(tagsToUpsert);
        }


        List<String> constituentIdsToRehydrate = assetIdToConstituentIdMap.values();
        List<Constituent__c> rehydratedConstituents = [SELECT Id, Constituent_Id__c FROM Constituent__c WHERE Constituent_Id__c IN :constituentIdsToRehydrate];
        Map<String, Id> constituentIdWithIdMap = new Map<String, Id>();

        for(Constituent__c cnst : rehydratedConstituents) {
            constituentIdWithIdMap.put(cnst.Constituent_Id__c, cnst.Id);
        }

        List<String> tagIdsToRehydrate = assetIdToTagIdMap.values();
        List<Tag__c> rehydratedTags = [SELECT Id, AAT__c FROM Tag__c WHERE AAT__c IN :tagIdsToRehydrate];
        Map<String, Id> tagIdWithIdMap = new Map<String, Id>();

        for(Tag__c tag : rehydratedTags) {
            tagIdWithIdMap.put(tag.AAT__c, tag.Id);
        }

        for(Asset ast : assetsToUpsert) {
            String assetConstituent = assetIdToConstituentIdMap.get(ast.Object_ID__c);
            String assetTag = assetIdToTagIdMap.get(ast.Object_ID__c);

            ast.Primary_Constituent__c = constituentIdWithIdMap.get(assetConstituent);
            ast.Tag__c = tagIdWithIdMap.get(assetTag);
        }

        if(assetsToUpsert.size() > 0) {
            return assets.upsertAssetsAndReturnInfoMap(assetsToUpsert);
        }
        
        return null;
    }

    public static String nullCheck(String value) {
        return value == null ? 'Not Provided' : value;
    }

    public class DepartmentsWrapper {
        public List<DepartmentWrapper> departments;
    }

    public class DepartmentWrapper {
        public Integer departmentId;
        public String displayName;
    }

    public class SearchWrapper {
        public Integer total;
        public List<Integer> objectIDs;
    }
}