force-app/chapter00/default/objects/Asset/fields/Asset_URL__c.field-meta.xml
<CustomField>
    <fullName>Asset_URL__c</fullName>
    <description>The asset&apos;s URL, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Asset URL</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The Department the asset is located in, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Is_Public_Domain__c.field-meta.xml
<CustomField>
    <fullName>Is_Public_Domain__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The determination as to whether an asset is in the public domain, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Is Public Domain</label>
    <type>Checkbox</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Object_ID__c.field-meta.xml
<CustomField>
    <fullName>Object_ID__c</fullName>
    <description>The Object ID for an asset, provided by The Metropolitan&apos;s Open Access API.</description>
    <externalId>true</externalId>
    <label>Object ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Primary_Image_Small__c.field-meta.xml
<CustomField>
    <fullName>Primary_Image_Small__c</fullName>
    <description>The URL for the small version of the Primary Image, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Primary Image Small</label>
    <type>Url</type>
</CustomField>

force-app/chapter08/default/classes/AssetSelector.cls
public with sharing class AssetSelector extends Util_Query {
    public static final String assetsByAccount = 'SELECT Id, Name, Department__c, Description, Is_Public_Domain__c, Object_Id__c, Asset_URL__c, Primary_Image_Small__c FROM Asset WHERE AccountId = :accountId LIMIT :lim OFFSET :offset';

    public List<Asset> retrieveAssetsByAccount(Id accountId, Integer lim, Integer offset) {
        Map<String, Object> bindMap = new Map<String, Object>{
            'accountId' => accountId,
            'lim' => lim,
            'offset' => offset
        };

        List<Asset> queryResult = (List<Asset>) queryWithBinds(assetsByAccount, bindMap, AccessLevel.SYSTEM_MODE);
        
        return queryResult;
    }

    public Integer countAssets(Id accountId) {
        return [SELECT COUNT() FROM Asset WHERE AccountId = :accountId];
    }
}