force-app/chapter00/default/objects/Asset/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The Department the asset is located in, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Is_Public_Domain__c.field-meta.xml
<CustomField>
    <fullName>Is_Public_Domain__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The determination as to whether an asset is in the public domain, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Is Public Domain</label>
    <type>Checkbox</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Object_ID__c.field-meta.xml
<CustomField>
    <fullName>Object_ID__c</fullName>
    <description>The Object ID for an asset, provided by The Metropolitan&apos;s Open Access API.</description>
    <externalId>true</externalId>
    <label>Object ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Primary_Image__c.field-meta.xml
<CustomField>
    <fullName>Primary_Image__c</fullName>
    <description>The Primary Image URL as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Primary Image</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary asset tag, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Tag</label>
    <referenceTo>Tag__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/chapter00/default/objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <description>An object to classify assets by tag.</description>
    <label>Tag</label>
    <nameField>
        <label>Tag Term</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/chapter04/default/classes/TagSelector.cls
public with sharing class TagSelector extends Util_Query {
    private static final String TAGS_WITH_ASSETS_BY_ACCOUNT_QUERY = 'SELECT Id, Name, (SELECT Id, Name, Department__c, Description, Is_Public_Domain__c, Object_Id__c, Primary_Image__c FROM Assets__r WHERE AccountId = :accountId) FROM Tag__c';

    public List<Tag__c> tagsWithAssetsByAccount(Id accountId) {
        Map<String, Object> bindMap = new Map<String, Object>{
            'accountId' => accountId
        };

        List<Tag__c> queryResult = (List<Tag__c>) queryWithBinds(TAGS_WITH_ASSETS_BY_ACCOUNT_QUERY, bindMap, AccessLevel.SYSTEM_MODE);
        
        return queryResult;
    }
}