force-app/chapter00/default/objects/Asset/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>The Department the asset is located in, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Is_Public_Domain__c.field-meta.xml
<CustomField>
    <fullName>Is_Public_Domain__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The determination as to whether an asset is in the public domain, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Is Public Domain</label>
    <type>Checkbox</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Object_ID__c.field-meta.xml
<CustomField>
    <fullName>Object_ID__c</fullName>
    <description>The Object ID for an asset, provided by The Metropolitan&apos;s Open Access API.</description>
    <externalId>true</externalId>
    <label>Object ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Primary_Image__c.field-meta.xml
<CustomField>
    <fullName>Primary_Image__c</fullName>
    <description>The Primary Image URL as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Primary Image</label>
    <type>Url</type>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary asset tag, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Tag</label>
    <referenceTo>Tag__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/chapter00/default/objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <description>An object to classify assets by tag.</description>
    <label>Tag</label>
    <nameField>
        <label>Tag Term</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/chapter04/default/classes/AssetsByTagService.cls
public with sharing class AssetsByTagService {
    public List<Tag__c> getTagsWithAssetsByAccount(Id accountId){
        return new TagSelector().tagsWithAssetsByAccount(accountId);
    }

    public List<AssetWrapperCh04> getTagsWithAssetsWrappersByAccount(Id accountId){
        List<Tag__c> tagList = new TagSelector().tagsWithAssetsByAccount(accountId);
        List<AssetWrapperCh04> assetWrapperList = new List<AssetWrapperCh04>();

        for(Tag__c tag : tagList) {
            TagWrapperCh04 wrappedTag = new TagWrapperCh04(tag);

            assetWrapperList.addAll(wrappedTag.assets);
        }

        return assetWrapperList;
    }

    public class TagWrapperCh04 {
        @AuraEnabled public List<AssetWrapperCh04> assets;

        public TagWrapperCh04(Tag__c tagToWrap) {
            this.assets = new List<AssetWrapperCh04>();

            for(Asset ast : tagToWrap.Assets__r) {
                AssetWrapperCh04 assetWrapper = new AssetWrapperCh04(ast);
                assetWrapper.tagId = tagToWrap.Id;
                assetWrapper.tagName = tagToWrap.Name;
                this.assets.add(assetWrapper);
            }
        }
    }

    public class AssetWrapperCh04 {
        @AuraEnabled public String tagId;
        @AuraEnabled public String tagName;
        @AuraEnabled public String assetId;
        @AuraEnabled public String assetName;
        @AuraEnabled public String assetDepartment;
        @AuraEnabled public String assetDescription;
        @AuraEnabled public String assetObjectId;
        @AuraEnabled public Boolean assetIsPublicDomain;
        @AuraEnabled public String assetPrimaryImage;
        
        public AssetWrapperCh04(Asset ast) {
            this.assetId = ast.Id;
            this.assetName = ast.Name;
            this.assetDepartment = ast.Department__c;
            this.assetDescription = ast.Description;
            this.assetIsPublicDomain = ast.Is_Public_Domain__c;
            this.assetObjectId = ast.Object_Id__c;
            this.assetPrimaryImage = ast.Primary_Image__c;
        }
    }
}