force-app/chapter00/default/objects/Asset/fields/Object_ID__c.field-meta.xml
<CustomField>
    <fullName>Object_ID__c</fullName>
    <description>The Object ID for an asset, provided by The Metropolitan&apos;s Open Access API.</description>
    <externalId>true</externalId>
    <label>Object ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/chapter00/default/objects/Asset/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary asset tag, as provided by The Metropolitan&apos;s Open Access API.</description>
    <label>Tag</label>
    <referenceTo>Tag__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/chapter00/default/objects/Constituent__c/Constituent__c.object-meta.xml
<CustomObject>
    <description>A custom object to hold information about the artist for each asset.</description>
    <label>Constituent</label>
    <nameField>
        <label>Constituent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constituents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/chapter00/default/objects/Constituent__c/fields/Constituent_ID__c.field-meta.xml
<CustomField>
    <fullName>Constituent_ID__c</fullName>
    <description>The external ID for The Metropolitan&apos;s Open Access database.</description>
    <externalId>true</externalId>
    <label>Constituent ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/chapter00/default/objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <description>An object to classify assets by tag.</description>
    <label>Tag</label>
    <nameField>
        <label>Tag Term</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/chapter00/default/objects/Tag__c/fields/AAT__c.field-meta.xml
<CustomField>
    <fullName>AAT__c</fullName>
    <description>The AAT number, as provided by The Metropolitan&apos;s Open Access API.</description>
    <formula>SUBSTITUTE(AAT_URL__c, &apos;http://vocab.getty.edu/page/aat/&apos;, &apos;&apos;)</formula>
    <label>AAT</label>
    <type>Text</type>
</CustomField>

force-app/chapter05/default/classes/AddAssetAccess.cls
public with sharing class AddAssetAccess extends Util_DML {

    public String getDepartments() {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:The_Met_Named/departments');
        request.setMethod('GET');
        HttpResponse response = http.send(request);

        if(response.getStatusCode() == 200) {
            return response.getBody();
        }
        return null;
    }

    public String searchByTerm(String searchTerm, Integer departmentId) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:The_Met_Named/search?q=' + String.escapeSingleQuotes(searchTerm) + '&departmentId=' + departmentId);
        request.setMethod('GET');
        HttpResponse response = http.send(request);

        if(response.getStatusCode() == 200) {
            return response.getBody();
        }
        return null;
    }

    public String getSearchedAssetInfo(Integer objectId) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:The_Met_Named/objects/' + objectId);
        request.setMethod('GET');
        HttpResponse response = http.send(request);

        if(response.getStatusCode() == 200) {
            return response.getBody();
        }
        return null;
    }

    public void upsertConstituents(List<Constituent__c> constituentsToUpsert) {
        try{
            upsertRecords(constituentsToUpsert, 'Constituent_Id__c');
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public void upsertTags(List<Tag__c> tagsToUpsert) {
        try {
            upsertRecords(tagsToUpsert, 'AAT__c');
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public Map<Integer, String> upsertAssets(List<Asset> assetsToUpsert) {
        Map<Integer, String> assetInfoMap = new Map<Integer, String>();

        try{
            List<Database.upsertResult> upsertResults = upsertRecords(assetsToUpsert, 'Object_ID__c');

            List<Id> idList = new List<Id>();

            for(Database.upsertResult ur : upsertResults) {
                if(ur.isCreated() && ur.isSuccess()) {
                    idList.add(ur.getId());
                }
            }

            if(idList.size() > 0) {
                for(Asset ast : [SELECT Id, Name, Object_ID__c FROM Asset WHERE Id IN :idList]) {
                    assetInfoMap.put(Integer.valueOf(ast.Object_ID__c), ast.Name);
                }
            } else {
                return null;
            }
        } catch (Exception e) {
            //error processing
        }

        return assetInfoMap;
    }
}