force-app/chapter00/default/objects/Consumer_Inquiry__c/Consumer_Inquiry__c.object-meta.xml
<CustomObject>
    <description>A junction object to track the inquiries by either a Customer or Contact.</description>
    <label>Consumer Inquiry</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Consumer Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumer Inquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/chapter00/default/objects/Consumer_Inquiry__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Consumer Inquiries</relationshipLabel>
    <relationshipName>Consumer_Inquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consumer_Inquiry__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tracks each reach out by Customer on an asset.</description>
    <label>Customer</label>
    <referenceTo>Customer</referenceTo>
    <relationshipLabel>Consumer Inquiries</relationshipLabel>
    <relationshipName>Consumer_Inquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/chapter10/default/classes/CustomerConsumer.cls
public with sharing class CustomerConsumer extends Consumer {
    public Id assetId;
    public Id consumerId;
    public Customer consumer;

    public CustomerConsumer(Id assetId, SObject consumer) {
        this.assetId = assetId;
        this.consumerId = consumerId;
        this.consumer = (Customer) consumer;
    }

    public override String getFact() {
        return String.valueOf(this.consumer.TotalLifeTimeValue);
    }

    public override Consumer_Inquiry__c getConsumerInquiry() {
        return new Consumer_Inquiry__c(Asset__c = this.assetId, Customer__c = this.consumerId);
    }
}