force-app/chapter00/default/objects/Consumer_Inquiry__c/Consumer_Inquiry__c.object-meta.xml
<CustomObject>
    <description>A junction object to track the inquiries by either a Customer or Contact.</description>
    <label>Consumer Inquiry</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Consumer Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumer Inquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/chapter00/default/objects/Consumer_Inquiry__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Consumer Inquiries</relationshipLabel>
    <relationshipName>Consumer_Inquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/chapter00/default/objects/Consumer_Inquiry__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tracks each time a Contact reaches out about an asset.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consumer Inquiries</relationshipLabel>
    <relationshipName>Consumer_Inquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/chapter10/default/classes/ContactConsumer.cls
public with sharing class ContactConsumer extends Consumer {
    public Id assetId;
    public Id consumerId;
    public Contact consumer;

    public ContactConsumer(Id assetId, SObject consumer) {
        this.assetId = assetId;
        this.consumerId = consumerId;
        this.consumer = (Contact) consumer;
    }

    public override String getFact() {
        return this.consumer.Account.Name;
    }

    public override Consumer_Inquiry__c getConsumerInquiry() {
        return new Consumer_Inquiry__c(Asset__c = this.assetId, Contact__c = this.consumerId);
    }
}